-- DAY 4: Ownership in AI-Driven Workflows
DELETE FROM curriculum_days WHERE program_id = '7da8d569-d5a3-47d8-9101-e8142b44822e' AND day_number = 4;

INSERT INTO curriculum_days (program_id, day_number, title, theme, day_objective)
VALUES (
  '7da8d569-d5a3-47d8-9101-e8142b44822e',
  4,
  'Ownership in AI-Driven Workflows',
  'AI may generate the work, but you own the outcome.',
  'Today you will internalize professional accountability. You will shift from a submission mindset to an ownership mindset.'
);

DO $$
DECLARE
  v_day_id uuid;
  v_section_id uuid;
BEGIN
  SELECT id INTO v_day_id FROM curriculum_days
  WHERE program_id = '7da8d569-d5a3-47d8-9101-e8142b44822e' AND day_number = 4;

  -- Section 1: Reality Mapping
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 1, 'reality_briefing', 'Reality Mapping',
    '[{"text": "AI produces drafts. AI summarizes information. AI drafts communication. AI suggests recommendations. AI accelerates delivery.", "type": "facilitator_script"}, {"text": "But: AI does NOT approve decisions. AI does NOT absorb consequences. AI does NOT protect relationships.", "type": "facilitator_script"}, {"text": "Humans do.", "type": "callout"}]'::jsonb
  );

  -- Section 2: Workplace Scenario
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 2, 'workplace_scenario', 'Workplace Scenario',
    '[{"text": "You use AI to draft a client proposal summary. The document looks polished and persuasive. You forward it without careful review.", "type": "facilitator_script"}, {"text": "Later, the client questions incorrect assumptions embedded in the proposal.", "type": "facilitator_script"}, {"text": "Your manager asks, \"Did you validate this?\"", "type": "facilitator_script"}, {"text": "This is not an AI failure. It is an ownership failure.", "type": "callout"}]'::jsonb
  );

  -- Section 3: Decision Challenge
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 3, 'decision_challenge', 'Decision Challenge',
    '[{"text": "Before sending work generated by AI, what responsibility must you assume?", "type": "facilitator_script"}, {"text": "What does professional due diligence look like?", "type": "facilitator_script"}]'::jsonb
  )
  RETURNING id INTO v_section_id;

  INSERT INTO curriculum_exercises (section_id, sort_order, question, question_type, options, thinking_prompts)
  VALUES
    (v_section_id, 1, 'You forwarded an AI-drafted proposal that contained incorrect assumptions. Who is responsible?', 'multiple_choice',
     '[{"label": "A", "text": "The AI system that generated the draft", "is_best": false}, {"label": "B", "text": "Your manager who assigned the task", "is_best": false}, {"label": "C", "text": "You, because you forwarded it without validation", "is_best": true}, {"label": "D", "text": "The client for not providing clearer requirements", "is_best": false}]'::jsonb,
     NULL),
    (v_section_id, 2, 'What steps constitute professional due diligence before sending AI-generated work?', 'open_ended', NULL,
     '["verify accuracy?", "assess tone?", "check assumptions?", "consider audience?"]'::jsonb),
    (v_section_id, 3, 'How does the shift from submission mindset to ownership mindset change your daily behavior?', 'open_ended', NULL,
     '["review habits?", "quality standards?", "accountability signals?", "trust building?"]'::jsonb);

  -- Section 4: Artifact Creation
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 4, 'artifact_creation', 'Artifact Creation: Pre-Submission Ownership Statement',
    '[{"text": "Write a \"Pre-Submission Ownership Statement.\"", "type": "facilitator_script"}, {"text": "In full sentences, describe the steps you must take before forwarding AI-assisted work. Explain how you verify accuracy, assess risk, adjust tone, and ensure contextual alignment.", "type": "facilitator_script"}, {"text": "This document becomes part of your personal operating system.", "type": "callout"}]'::jsonb
  );

  -- Section 5: Reflection
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 5, 'reflection', 'Reflection',
    '[{"text": "Take a moment to reflect on today''s lesson.", "type": "facilitator_script"}]'::jsonb
  )
  RETURNING id INTO v_section_id;

  INSERT INTO curriculum_exercises (section_id, sort_order, question, question_type)
  VALUES
    (v_section_id, 1, 'Do you default to speed or responsibility?', 'reflection'),
    (v_section_id, 2, 'Where have you previously assumed that technology would "cover you"?', 'reflection');

  -- Section 6: Professional Upgrade
  INSERT INTO curriculum_sections (day_id, sort_order, section_type, title, content)
  VALUES (
    v_day_id, 6, 'professional_upgrade', 'Professional Upgrade',
    '[{"text": "Ownership builds trust faster than brilliance.", "type": "facilitator_script"}, {"text": "In AI-powered teams, accountability is a leadership signal.", "type": "callout"}]'::jsonb
  );

END $$;
